NAME =		ex02

INCLUDES =	MutantStack.hpp

SRC =		main.cpp

COMP = clang++
CFLAGS	= -Wall -Wextra -Werror -std=c++98 

all: $(NAME)

$(NAME): $(SRC) $(INCLUDES)
	$(COMP) $(CFLAGS) $(SRC) -o $(NAME) -I.